web:
  build: .
  command: bash -c "sleep 2 && npm start"
  volumes:
    - ./:/app
  ports:
    - "3000:3000"
  links:
    - mongo 
  environment:
    PORT: 3000
    NODE_ENV: prod  
  
mongo:
  image: mongo
  ports:
    - "27017:27017"

# Set Up MongoDB

# mongosetup:
#  build: ./mongoSetUp
#  links:
#    - mongo